name: Compile CV and upload PDF

on:
  workflow_dispatch:
  push:
    paths:
      - CV/*.tex
      - .github/workflows/compile_cv.yaml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: CV/cv_ryota_maeda.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: CV
          path: CV/cv_ryota_maeda.pdf

  push:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Set up
        uses: actions/checkout@v3

      - name: Download PDF file
        uses: actions/download-artifact@v3
        with:
          name: CV
          path: CV

      - name: Push PDF to GitHub
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          if [ -f "CV/cv_ryota_maeda.pdf" ]; then
            git add CV/cv_ryota_maeda.pdf
            git commit -m "Update CV"
            git push
          else
            echo "CV/cv_ryota_maeda.pdf not found"
          fi
